### ISSUE TITLE
Magepow product zoom not working in magento 2.3.3

### ISSUE THREAD

**Issue by Lokiviper** [magepow/magento-2-product-zoom#1]
Hello team..
I have installed magepow extension for my website myflowersbox.com and it is enabled from admin panel but still product zoom is not working..

Kindly look into this matter immediately..your support will be very helpful..

Thank you..

**Comment by magiccart** [comment]
I have checked your site using a custom theme change structure different default theme Luma so product zoom not work. You can config the theme to Luma will see how to product zoom work.
