### ISSUE TITLE
Help - How to force this extension to override the theme

### ISSUE THREAD

**Issue by davirs** [magepow/magento-2-product-zoom#1]
I installed this zoom, I did the configurations and default procedures is OK, but there is no changes at frontend...

How I force this extension to "override" the current theme layout?

This is a great extension!!! Thank you

**Comment by magiccart** [comment]
Hi, If your theme using the default slider "fotorama slider" of Magento the product zoom will auto works. You try config to the Luma theme and check it. You can refer guide apply to the Luma theme as a guide here: https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-apply.html

**Comment by davirs** [comment]
Inside luma it's working! I thing it's not compatible with my theme.

One more question, how can I configure the default zoom size for inner zoom without scroll and lens?

**Comment by magiccart** [comment]
Hi, You can config size with Lens Size default value is 200.
